# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /home/gmek/UnrealEngine

TARGETS = \
	Zombie-Android-DebugGame  \
	Zombie-Android-Development  \
	Zombie-Android-Shipping  \
	Zombie-Linux-DebugGame  \
	Zombie-Linux-Development  \
	Zombie-Linux-Shipping  \
	Zombie-LinuxArm64-DebugGame  \
	Zombie-LinuxArm64-Development  \
	Zombie-LinuxArm64-Shipping  \
	Zombie \
	ZombieEditor-Linux-DebugGame  \
	ZombieEditor-Linux-Development  \
	ZombieEditor \
	LiveLinkHub-Linux-DebugGame  \
	LiveLinkHub-Linux-Development  \
	LiveLinkHub \
	DotNetPerforceLib \
	EventLoopUnitTests \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Development  \
	UnrealEditor \
	UnrealGame-Android-DebugGame  \
	UnrealGame-Android-Development  \
	UnrealGame-Android-Shipping  \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Development  \
	UnrealGame-Linux-Shipping  \
	UnrealGame-LinuxArm64-DebugGame  \
	UnrealGame-LinuxArm64-Development  \
	UnrealGame-LinuxArm64-Shipping  \
	UnrealGame\
	configure

BUILD = "$(UNREALROOTPATH)/Engine/Build/BatchFiles/RunUBT.sh"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend ZombieEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug ZombieEditor-Linux-Debug


Zombie-Android-DebugGame:
	 $(BUILD) Zombie Android DebugGame  -Project="/home/gmek/Dev/UnrealEngine/Zombie/Zombie.uproject" $(ARGS)

Zombie-Android-Development:
	 $(BUILD) Zombie Android Development  -Project="/home/gmek/Dev/UnrealEngine/Zombie/Zombie.uproject" $(ARGS)

Zombie-Android-Shipping:
	 $(BUILD) Zombie Android Shipping  -Project="/home/gmek/Dev/UnrealEngine/Zombie/Zombie.uproject" $(ARGS)

Zombie-Linux-DebugGame:
	 $(BUILD) Zombie Linux DebugGame  -Project="/home/gmek/Dev/UnrealEngine/Zombie/Zombie.uproject" $(ARGS)

Zombie-Linux-Development:
	 $(BUILD) Zombie Linux Development  -Project="/home/gmek/Dev/UnrealEngine/Zombie/Zombie.uproject" $(ARGS)

Zombie-Linux-Shipping:
	 $(BUILD) Zombie Linux Shipping  -Project="/home/gmek/Dev/UnrealEngine/Zombie/Zombie.uproject" $(ARGS)

Zombie-LinuxArm64-DebugGame:
	 $(BUILD) Zombie LinuxArm64 DebugGame  -Project="/home/gmek/Dev/UnrealEngine/Zombie/Zombie.uproject" $(ARGS)

Zombie-LinuxArm64-Development:
	 $(BUILD) Zombie LinuxArm64 Development  -Project="/home/gmek/Dev/UnrealEngine/Zombie/Zombie.uproject" $(ARGS)

Zombie-LinuxArm64-Shipping:
	 $(BUILD) Zombie LinuxArm64 Shipping  -Project="/home/gmek/Dev/UnrealEngine/Zombie/Zombie.uproject" $(ARGS)

Zombie: Zombie-Linux-Development

ZombieEditor-Linux-DebugGame:
	 $(BUILD) ZombieEditor Linux DebugGame  -Project="/home/gmek/Dev/UnrealEngine/Zombie/Zombie.uproject" $(ARGS)

ZombieEditor-Linux-Development:
	 $(BUILD) ZombieEditor Linux Development  -Project="/home/gmek/Dev/UnrealEngine/Zombie/Zombie.uproject" $(ARGS)

ZombieEditor: ZombieEditor-Linux-Development

LiveLinkHub-Linux-DebugGame:
	 $(BUILD) LiveLinkHub Linux DebugGame  $(ARGS)

LiveLinkHub-Linux-Development:
	 $(BUILD) LiveLinkHub Linux Development  $(ARGS)

LiveLinkHub: LiveLinkHub-Linux-Development

DotNetPerforceLib: DotNetPerforceLib-Linux-Development

EventLoopUnitTests: EventLoopUnitTests-Linux-Development

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  $(ARGS)

UnrealEditor-Linux-Development:
	 $(BUILD) UnrealEditor Linux Development  $(ARGS)

UnrealEditor: UnrealEditor-Linux-Development

UnrealGame-Android-DebugGame:
	 $(BUILD) UnrealGame Android DebugGame  $(ARGS)

UnrealGame-Android-Development:
	 $(BUILD) UnrealGame Android Development  $(ARGS)

UnrealGame-Android-Shipping:
	 $(BUILD) UnrealGame Android Shipping  $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  $(ARGS)

UnrealGame-Linux-Development:
	 $(BUILD) UnrealGame Linux Development  $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  $(ARGS)

UnrealGame-LinuxArm64-DebugGame:
	 $(BUILD) UnrealGame LinuxArm64 DebugGame  $(ARGS)

UnrealGame-LinuxArm64-Development:
	 $(BUILD) UnrealGame LinuxArm64 Development  $(ARGS)

UnrealGame-LinuxArm64-Shipping:
	 $(BUILD) UnrealGame LinuxArm64 Shipping  $(ARGS)

UnrealGame: UnrealGame-Linux-Development

configure:
	$(BUILD) -ProjectFiles -Project="/home/gmek/Dev/UnrealEngine/Zombie/Zombie.uproject" -Game 

.PHONY: $(TARGETS)
